feat(android): Add detail screen in the sample
mobilejazz/harmony-kotlin pull request #81
Opened 2022-04-01 14:26 UTC by jfilowk

**[CAN BE MERGED]**

2022-04-05 14:56 UTC, franmontiel requested changes

2022-04-06 09:07 UTC, jfilowk commented on sample-android/src/main/res/layout/activity_hacker_post_detail.xml
> +          android:text="@string/ls_lorem"
HackerNews have different types of post and some of them doesn't have content.

2022-04-06 10:23 UTC, franmontiel approved these changes

2022-04-06 11:20 UTC, joselufo approved these changes

2022-04-06 11:20 UTC, merged