Feature/error simplification
mobilejazz/harmony-kotlin pull request #83
Opened 2022-04-21 12:06 UTC by franmontiel

Redefinition of Exceptions to simplify them and make them work better after Either implementation.

 - Simplified hierarchy & modify it to work better with eitherOf
   - Separated developing errors from HarmonyException (our controlled ones) 
 - Removed DomainException (all exceptions should be considered domain ones)
   - If needed to create a custom exception in a project just inherit from HarmonyException)
 - Renamed MappingException to DataSerializationException
   - Name was too generic and the only purpose of that exception was to wrap any possible serialization/deserialization exceptions.
 - Renamed OperationNotAllowedException to OperationNotSupportedException
   - To be consistent with QueryNotSupportedException 
 - Removed duplicated of the functions `notSupportedQuery` & `notSupportedOperation` 
 - HarmonyException is now abstract to avoid instantiating it directly 
   - We just need it for acting as a parent of all our controlled exception but we don't want to throw it directly.

Check [HarmonyException](https://github.com/mobilejazz/harmony-kotlin/blob/95cd92016f2a66fa4e054ff7b2a6786da179e3ed/harmony-kotlin/src/commonMain/kotlin/com.harmony.kotlin/error/HarmonyException.kt) to see all available errors on Harmony.

2022-04-26 10:48 UTC, joselufo requested changes

2022-04-26 10:48 UTC, joselufo commented on harmony-kotlin/src/commonMain/kotlin/com.harmony.kotlin/error/HarmonyException.kt
> +class DataSerializationException(message: String? = null, cause: Throwable? = null) : DataNotAvailableException(message, cause)
Better to create a different kotlin file for the `DataNotAvailableException`.

2022-04-26 10:48 UTC, joselufo commented on harmony-kotlin/src/commonMain/kotlin/com.harmony.kotlin/error/HarmonyException.kt
> +class HttpException(val statusCode: Int, val response: String?) : HarmonyException()
Better to move it to the network package within the data package.

2022-04-26 10:48 UTC, joselufo commented on harmony-kotlin/src/commonMain/kotlin/com.harmony.kotlin/error/HarmonyException.kt
> +// endregion
Better to have it in a different kotlin file, it could be called `RuntimeExceptions.kt`

2022-04-26 10:48 UTC, joselufo commented on harmony-kotlin/src/commonTest/kotlin/com/harmony/kotlin/data/repository/CacheRepositoryTests.kt
> +  fun `should obtain the value from main when using CacheSyncOperation given that cache get() throws DataSerializationException`() =
do not add `()` symbols as it generates a warning.

2022-05-03 11:02 UTC, joselufo approved these changes
All Ok

2022-05-06 07:54 UTC, migueltorcha approved these changes

2022-05-06 08:00 UTC, merged