Feature/either implementation
mobilejazz/harmony-kotlin pull request #84
Opened 2022-04-21 12:07 UTC by franmontiel

This PR contains all the necessary to start using Either at the generic interactor level.
* Either class
* eitherOf method that transform a block of code into a Either
* Generic interactor implementation returning Either
* Sample updated

Some errors modification were needed for this to work properly and they can be found in #83

2022-04-26 10:57 UTC, joselufo commented
I feel is everything OK but it's missing all the tests and we **must** have it before merging.

2022-04-26 10:58 UTC, joselufo requested changes
Missing all the unit tests

2022-05-03 11:03 UTC, joselufo approved these changes
All OK, still missing a lot of tests but we can work async with that.

2022-05-06 07:34 UTC, migueltorcha approved these changes

2022-05-06 08:24 UTC, merged